### PR TITLE
Translate into Chinese Traditional

### PR DESCRIPTION
**Pull request by osk2**
Hi, I translate app into Chinese Traditional

Let me know if I miss something 😬

### CODE REVIEW

**Comment by osk2** [comment]
ping @zacharee 

Can you take a look of this?

**Comment by zacharee** [comment]
I'm not accepting translations right now. I need to find a translation organization service first.

**Comment by zacharee** [comment]
Set up a Crowdin project https://crowdin.com/project/systemui-tuner

**Comment by osk2** [comment]
Will translate on Crowdin once I have time.

**Comment by osk2** [comment]
Translation already completed on Crowdin.

**Pull request closed without merging**
